@startuml
UserA -> "Clearable Token": orderTransfer(to: UserB)
"Clearable Token" -> Agent: ClearableTransferOrdered
UserB-> "Clearable Token" : rejectClearableTransfer
"Clearable Token" -> UserA: release held amount
"Clearable Token" -> UserA: ClearableTransferRejected
@enduml
